# Generated by Django 4.2.8 on 2023-12-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardQuest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Collection_date',
            new_name='collection_date',
        ),
    ]
